{
 "title": "istio-hongkong",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(istio_requests_total, request_host)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(istio_requests_total{request_host=~\"$host\"},destination_service)"
   },
   {
    "name": "service_cluster",
    "label": "service_cluster",
    "query": "query_result(sum(istio_requests_total{request_host=~\"$host\",destination_service=~\"$service\"}) by (destination_cluster) or sum(istio_tcp_sent_bytes_total{request_host=~\"$host\",destination_service=~\"$service\"}) by (destination_cluster))"
   },
   {
    "name": "qrep",
    "label": "Reporter",
    "query": "query_result(sum(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",destination_service=~\"$service\"}) by (reporter) or sum(istio_tcp_sent_bytes_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\", destination_service=~\"$service\"}) by (reporter))"
   },
   { "name": "srcns", "label": "Client Workload Namespace" },
   { "name": "srcwl", "label": "Client Workload" },
   {
    "name": "dstns",
    "label": "Service Workload Namespace",
    "query": "query_result(sum(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"destination\", destination_service=\"$service\"}) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"destination\", destination_service=~\"$service\"}) by (destination_workload_namespace))"
   },
   {
    "name": "dstwl",
    "label": "Service Workload",
    "query": "query_result( sum(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"destination\", destination_service=~\"$service\", destination_workload_namespace=~\"$dstns\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"destination\", destination_service=~\"$service\", destination_workload_namespace=~\"$dstns\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Host: $host</span>\n</div>"
   },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Host: $host</span>\n</div>"
  },
  {
   "title": "当前QPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "ops",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\",destination_service=~\"$service\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "SLA(non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\",destination_service=~\"$service\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\",destination_service=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Client Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_request_duration_milliseconds_sum{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))/sum(increase(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\",destination_service=~\"$service\"}[1m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  { "title": "Client Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>CLIENT WORKLOADS</span>\n</div>"
   },
   "content": "<div class=\"dashboard-header text-center\">\n<span>CLIENT WORKLOADS</span>\n</div>"
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",destination_service=~\"$service\",reporter=\"$qrep\",source_workload=~\"$srcwl\",source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} "
    }
   ]
  },
  {
   "title": "SLA",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\", destination_service=~\"$service\",response_code!~\"5.*\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace) / sum(irate(istio_requests_total{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=\"$qrep\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[5m])) by (source_workload, source_workload_namespace)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} "
    }
   ]
  },
  {
   "title": "Incoming Request Duration By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(1, sum(irate(istio_request_duration_milliseconds_bucket{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=~\"$qrep\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=~\"$qrep\", connection_security_policy=\"mutual_tls\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))"
    }
   ]
  },
  {
   "title": "Incoming Request Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(irate(istio_request_bytes_bucket{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=~\"$qrep\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Response Size By Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(irate(istio_response_bytes_bucket{request_host=~\"$host\",destination_cluster=~\"$service_cluster\",reporter=~\"$qrep\", destination_service=~\"$service\", source_workload=~\"$srcwl\", source_workload_namespace=~\"$srcns\"}[1m])) by (source_workload, source_workload_namespace, le))",
     "legendFormat": "{{source_workload}}.{{source_workload_namespace}} "
    }
   ]
  }
 ]
}